apiVersion: v1
kind: Service
metadata:
  name: {{ default "rmq-exporter" .Values.service_name }}
  labels:
    servicemonitor/rmq-exporter: ""
spec:
  clusterIP: None
  ports:
  - name: rmq-metrics
    port: rmq-metrics
    protocol: TCP
  selector:
    prometheus-exporter: rmq
