apiVersion: v1
kind: Service
metadata:
  name: {{ default "rmq-exporter" .Values.service_name }}
  labels:
    servicemonitor/rmq-exporter: ""
spec:
  clusterIP: None
  ports:
  - port: {{ default 5132 .Values.service_port }}
    protocol: TCP
  selector:
    prometheus-exporter: rmq
