apiVersion: v1
kind: Service
metadata:
  name: {{ default "redis-exporter" .Values.service_name }}
  labels:
    servicemonitor/redis-exporter: ""
spec:
  clusterIP: None
  ports:
  - port: redis-metrics
    protocol: TCP
  selector:
    prometheus-exporter: redis
