apiVersion: v1
kind: Service
metadata:
  name: {{ default "php-fpm-metrics" .Values.service_name }}
  labels:
    servicemonitor/php-fpm-exporter: ""
spec:
  clusterIP: None
  ports:
    - name: php-fpm-metrics
      port: php-fpm-metrics
      protocol: TCP
{{- end }}
  selector:
{{- range $key, $value := .Values.pod_labels }}
    {{ $key }}: {{ $value }}
{{- end }}
