apiVersion: v1
kind: Service
metadata:
  name: {{ default "mongodb-exporter" .Values.service_name }}
  labels:
    servicemonitor/mongodb-exporter: ""
spec:
  clusterIP: None
  ports:
  - name: mongodb-metrics
    port: mongodb-metrics
    protocol: TCP
  selector:
    prometheus-exporter: mongodb
