apiVersion: v1
kind: Service
metadata:
  name: {{ default "elasticsearch-exporter" .Values.service_name }}
  labels:
    servicemonitor/elasticsearch-exporter: ""
spec:
  clusterIP: None
  ports:
  - name: es-metrics
    port: es-metrics
    protocol: TCP
  selector:
    prometheus-exporter: elasticsearch
