apiVersion: v1
kind: Service
metadata:
  name: {{ default "elasticsearch-exporter" .Values.service_name }}
  labels:
    servicemonitor/elasticsearch-exporter: ""
spec:
  clusterIP: None
  ports:
  - port: {{ default 5132 .Values.port }}
    protocol: TCP
  selector:
    prometheus-exporter: elasticsearch
